import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, ArrowUpRight, Building2, CreditCard, Globe2, SearchCheck, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FlowSteps, PageIntro, SafetyNote } from "@/components/flow";
import { useDemo } from "@/lib/demo-context";
export const Route = createFileRoute("/verify")({ head: () => ({ meta: [{ title: "Verify Before You Act — InvestorSafe AI" }, { name: "description", content: "Use official Indian investor and cybercrime resources to verify details found in a suspicious investment message." }, { property: "og:title", content: "Verify Before You Act — InvestorSafe AI" }, { property: "og:description", content: "Check details through appropriate official sources before taking action." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: VerifyPage });
const cards = [
 {icon:Building2, tag:"ENTITY CHECK", title:"Trading App / Intermediary", text:"Check whether the entity is registered with SEBI.", button:"Official SEBI Verification", href:"https://www.sebi.gov.in/intermediaries.html"},
 {icon:CreditCard, tag:"PAYMENT CHECK", title:"UPI / Bank / Payment Detail", text:"Use the relevant official verification mechanism before making a payment. SEBI investor resources can help you understand safe payment practices.", button:"SEBI Check", href:"https://investor.sebi.gov.in/"},
 {icon:SearchCheck, tag:"IDENTIFIER CHECK", title:"Phone / Email / UPI / URL", text:"Check whether the identifier appears in the available cybercrime suspect repository. Start at the official cybercrime portal.", button:"I4C Suspect Search", href:"https://cybercrime.gov.in/"},
 {icon:Globe2, tag:"LINK CHECK", title:"Website / Link", text:"Review the website carefully and avoid entering sensitive information until verified.", button:"Cybercrime Portal", href:"https://cybercrime.gov.in/"},
];
function VerifyPage() {const {analysis}=useDemo(); return <main className="page-wrap inner-page"><FlowSteps current={3}/><PageIntro eyebrow="STEP 04 / CHECK OFFICIAL SOURCES" title="Verify Before You Act" description="Use the appropriate official source to check the details found in the message."/>{analysis?.details.length ? <div className="verify-detected"><ShieldCheck className="size-5 text-primary"/><span>From your message: </span><strong>{analysis.details.map(d=>d.value).join("  ·  ")}</strong>{analysis.demo && <small>Includes labelled sample details</small>}</div> : null}<div className="verify-grid">{cards.map(({icon:Icon,tag,title,text,button,href})=><article className="verify-card" key={title}><div className="verify-icon"><Icon className="size-6" strokeWidth={1.8}/></div><span className="item-index">{tag}</span><h2>{title}</h2><p>{text}</p><Button asChild variant="outline" className="verify-link"><a href={href} target="_blank" rel="noopener noreferrer">{button}<ArrowUpRight/></a></Button></article>)}</div><div className="mt-8"><SafetyNote>An absence from a database does not prove that something is genuine. We do not perform or display any official verification result.</SafetyNote></div><div className="mt-9 flex flex-wrap gap-4"><Button asChild size="lg"><Link to="/safety">Continue to Safety Guide <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><Link to="/results"><ArrowLeft/> Back to Results</Link></Button></div></main> }
